# Since Azure Pipelines does not support YAML anchors as of May 2019,
# we use job and step templates, Azure Pipelines' mini language, instead here.
# It is a domain specific language built upon YAML, and has quite complex
# things.  Read the docs first:
#   https://docs.microsoft.com/azure/devops/pipelines/process/templates
# Template files are placed in the .azure-pipelines/ directory.
variables:
  configuration: Release

jobs:

- job: Windows_Mono
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono2
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono3
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono4
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono5
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono6
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono7
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30

- job: Windows_Mono8
  pool:
    vmImage: windows-2019
  steps:
  - task: CmdLine@2
    displayName: choco install mono
    inputs:
      script: choco install mono --yes
  - template: .azure-pipelines/windows-net471.yml
    parameters:
      configuration: $(configuration)
      turnServerUrl: $(turnServerUrl)
      testPrefix: '"$PROGRAMFILES/Mono/bin/mono.exe"'
      testArguments: -appdomains denied -stoponfail
      copySQLitePCLRaw: true
  timeoutInMinutes: 30
