parameters:
  configuration: Debug
  testDisplayName: xunit.console.exe *.Tests.dll
  testCommand: "mono --server xunit.runner.console.*/tools/net471/xunit.console.exe"
  testArguments: -verbose -parallel none

steps:

- task: Bash@3
  displayName: hooks/check-bom
  inputs:
    targetType: filePath
    filePath: hooks/check-bom

- task: NuGetCommand@2
  displayName: nuget install xunit.runner.console
  inputs:
    command: custom
    arguments: install xunit.runner.console

- task: CmdLine@2
  displayName: dotnet msbuild /restore
  inputs:
    script: |
      dotnet msbuild \
        /restore \
        /p:Configuration=${{ parameters.configuration }}

- task: CmdLine@2
  displayName: ${{ parameters.testDisplayName }}
  inputs:
    script: |
      ${{ parameters.testCommand }} \
        "$(pwd)"/*.Tests/bin/${{ parameters.configuration }}/net*/*.Tests.dll \
        ${{ parameters.testArguments }}
  env:
    TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
    MONO_THREADS_SUSPEND: preemptive
  timeoutInMinutes: 10
